"""Route-table snapshot: the full HTTP surface must not change by accident.

Freezes ``(path, methods, route-level-dependency-count)`` for every route; the count catches a route
that lost its ``dependencies=[require_scope(...)]`` gate. When a route is intentionally added,
removed or regated, update ``EXPECTED_ROUTES`` in the same commit.

The SPA catch-all (``/{full_path:path}``) is excluded: it is mounted only when a built
``frontend/dist`` exists, which CI's unit-test job lacks.
"""

from fastapi.routing import APIRoute, iter_route_contexts

from strata.server import app

# The SPA fallback mounts only when the frontend bundle exists; exclude it so the
# snapshot matches across dev and CI.
_EXCLUDED_PATHS = {"/{full_path:path}"}

EXPECTED_ROUTES = [
    ("/health", "GET", 0),
    ("/health/dependencies", "GET", 0),
    ("/health/ready", "GET", 0),
    ("/metrics", "GET", 0),
    ("/metrics/prometheus", "GET", 0),
    ("/metrics/tables", "GET", 1),
    ("/metrics/tables/{table_id:path}", "GET", 1),
    ("/oembed", "GET", 0),
    ("/p/{token}", "GET", 0),
    ("/p/{token}/archive.zip", "GET", 0),
    ("/p/{token}/badge.svg", "GET", 0),
    ("/p/{token}/data", "GET", 0),
    ("/p/{token}/embed", "GET", 0),
    ("/p/{token}/ro-crate", "GET", 0),
    ("/p/{token}/verify", "GET", 0),
    ("/v1/admin/notebook-workers", "GET", 1),
    ("/v1/admin/notebook-workers", "POST", 1),
    ("/v1/admin/notebook-workers", "PUT", 1),
    ("/v1/admin/notebook-workers/reload", "POST", 1),
    ("/v1/admin/notebook-workers/{worker_name}", "DELETE", 1),
    ("/v1/admin/notebook-workers/{worker_name}", "PATCH", 1),
    ("/v1/admin/notebook-workers/{worker_name}", "PUT", 1),
    ("/v1/admin/notebook-workers/{worker_name}/refresh", "POST", 1),
    ("/v1/admin/tenants", "GET", 1),
    ("/v1/admin/tenants/{tenant_id}", "GET", 1),
    ("/v1/artifacts", "GET", 0),
    ("/v1/artifacts", "PUT", 0),
    ("/v1/artifacts/builds/{build_id}", "GET", 0),
    ("/v1/artifacts/by-provenance/{provenance_hash}", "GET", 0),
    ("/v1/artifacts/by-provenance/{provenance_hash}", "PUT", 0),
    ("/v1/artifacts/download", "GET", 0),
    ("/v1/artifacts/explain-materialize", "POST", 0),
    ("/v1/artifacts/finalize", "POST", 0),
    ("/v1/artifacts/gc", "POST", 0),
    ("/v1/artifacts/import", "POST", 0),
    ("/v1/artifacts/import/blobs/{content_sha256}", "PUT", 0),
    ("/v1/artifacts/materialize", "POST", 0),
    ("/v1/artifacts/names/{name:path}/status", "GET", 0),
    ("/v1/artifacts/stats", "GET", 0),
    ("/v1/artifacts/upload", "POST", 0),
    ("/v1/artifacts/upload/{artifact_id}/v/{version}", "POST", 0),
    ("/v1/artifacts/usage", "GET", 0),
    ("/v1/artifacts/{artifact_id}/v/{version}", "DELETE", 0),
    ("/v1/artifacts/{artifact_id}/v/{version}", "GET", 0),
    ("/v1/artifacts/{artifact_id}/v/{version}/data", "GET", 0),
    ("/v1/artifacts/{artifact_id}/v/{version}/dependents", "GET", 0),
    ("/v1/artifacts/{artifact_id}/v/{version}/export", "POST", 0),
    ("/v1/artifacts/{artifact_id}/v/{version}/lineage", "GET", 0),
    ("/v1/artifacts/{artifact_id}/v/{version}/pin", "DELETE", 0),
    ("/v1/artifacts/{artifact_id}/v/{version}/pin", "POST", 0),
    ("/v1/artifacts/{artifact_id}/v/{version}/publish", "POST", 1),
    ("/v1/artifacts/{artifact_id}/v/{version}/tags", "GET", 0),
    ("/v1/artifacts/{artifact_id}/v/{version}/tags", "PUT", 0),
    ("/v1/artifacts/{artifact_id}/v/{version}/tags/{key}", "DELETE", 0),
    ("/v1/builds/{build_id}", "GET", 0),
    ("/v1/builds/{build_id}/finalize", "POST", 0),
    ("/v1/builds/{build_id}/log", "POST", 0),
    ("/v1/builds/{build_id}/manifest", "GET", 0),
    ("/v1/cache/clear", "POST", 1),
    # 1 dependency: require_scope("admin:cache"); the listing is cache-wide and exposes
    # every tenant's entry metadata.
    ("/v1/cache/entries", "GET", 1),
    ("/v1/cache/evictions", "GET", 0),
    ("/v1/cache/histogram", "GET", 1),
    ("/v1/cache/stats", "GET", 0),
    ("/v1/cache/warm", "POST", 0),
    ("/v1/cache/warm/async", "POST", 0),
    ("/v1/cache/warm/jobs", "GET", 0),
    ("/v1/cache/warm/jobs/{job_id}", "DELETE", 0),
    ("/v1/cache/warm/jobs/{job_id}", "GET", 0),
    ("/v1/config/timeouts", "GET", 0),
    # 1 dependency: require_scope("admin:cache"), for the same cross-tenant exposure.
    ("/v1/debug/cache/inspect", "GET", 1),
    ("/v1/debug/connections", "GET", 1),
    ("/v1/debug/gc/pauses", "GET", 1),
    ("/v1/debug/latency", "GET", 1),
    ("/v1/debug/memory", "GET", 1),
    ("/v1/debug/pools", "GET", 1),
    ("/v1/debug/rate-limits", "GET", 1),
    ("/v1/events", "GET", 0),
    ("/v1/logs", "GET", 1),
    ("/v1/logs/stream", "GET", 1),
    ("/v1/materialize", "POST", 0),
    ("/v1/metadata/cleanup", "POST", 1),
    ("/v1/metadata/stats", "GET", 0),
    ("/v1/names", "GET", 0),
    ("/v1/names", "POST", 0),
    ("/v1/names/{name:path}", "DELETE", 0),
    ("/v1/names/{name:path}", "GET", 0),
    ("/v1/names/{name:path}/aliases", "GET", 0),
    ("/v1/names/{name:path}/aliases/{alias}", "DELETE", 0),
    ("/v1/names/{name:path}/aliases/{alias}", "GET", 0),
    ("/v1/names/{name:path}/aliases/{alias}", "PUT", 0),
    ("/v1/notebooks/config", "GET", 1),
    ("/v1/notebooks/create", "POST", 1),
    ("/v1/notebooks/delete-by-path", "POST", 1),
    ("/v1/notebooks/discover", "GET", 1),
    ("/v1/notebooks/import", "POST", 1),
    ("/v1/notebooks/import-snapshot", "POST", 1),
    ("/v1/notebooks/open", "POST", 1),
    ("/v1/notebooks/recents/validate", "POST", 1),
    ("/v1/notebooks/sessions", "GET", 1),
    ("/v1/notebooks/sessions/{session_id}", "GET", 1),
    ("/v1/notebooks/{notebook_id}", "DELETE", 1),
    ("/v1/notebooks/{notebook_id}/artifacts", "GET", 1),
    ("/v1/notebooks/{notebook_id}/artifacts/{artifact_id}/v/{version}/promote", "POST", 1),
    ("/v1/notebooks/{notebook_id}/cells", "GET", 1),
    ("/v1/notebooks/{notebook_id}/cells", "POST", 1),
    ("/v1/notebooks/{notebook_id}/cells/reorder", "PUT", 1),
    ("/v1/notebooks/{notebook_id}/cells/{cell_id}", "DELETE", 1),
    ("/v1/notebooks/{notebook_id}/cells/{cell_id}", "PUT", 1),
    ("/v1/notebooks/{notebook_id}/cells/{cell_id}/data", "GET", 1),
    ("/v1/notebooks/{notebook_id}/cells/{cell_id}/data/export", "GET", 1),
    ("/v1/notebooks/{notebook_id}/cells/{cell_id}/data/summary", "GET", 1),
    ("/v1/notebooks/{notebook_id}/cells/{cell_id}/execute", "POST", 1),
    ("/v1/notebooks/{notebook_id}/cells/{cell_id}/iterations", "GET", 1),
    ("/v1/notebooks/{notebook_id}/cells/{cell_id}/outputs/{index}/blob", "GET", 1),
    ("/v1/notebooks/{notebook_id}/cells/{cell_id}/tests", "POST", 1),
    ("/v1/notebooks/{notebook_id}/cells/{cell_id}/tests", "PUT", 1),
    ("/v1/notebooks/{notebook_id}/connections", "GET", 1),
    ("/v1/notebooks/{notebook_id}/connections", "PUT", 1),
    ("/v1/notebooks/{notebook_id}/connections/{name}/schema", "GET", 1),
    ("/v1/notebooks/{notebook_id}/dag", "GET", 1),
    ("/v1/notebooks/{notebook_id}/dependencies", "GET", 1),
    ("/v1/notebooks/{notebook_id}/dependencies", "POST", 1),
    ("/v1/notebooks/{notebook_id}/dependencies/{package_name}", "DELETE", 1),
    ("/v1/notebooks/{notebook_id}/env", "PUT", 1),
    ("/v1/notebooks/{notebook_id}/environment", "GET", 1),
    ("/v1/notebooks/{notebook_id}/environment/environment.yaml", "POST", 1),
    ("/v1/notebooks/{notebook_id}/environment/environment.yaml/preview", "POST", 1),
    ("/v1/notebooks/{notebook_id}/environment/jobs", "POST", 1),
    ("/v1/notebooks/{notebook_id}/environment/jobs/current", "GET", 1),
    ("/v1/notebooks/{notebook_id}/environment/requirements.txt", "GET", 1),
    ("/v1/notebooks/{notebook_id}/environment/requirements.txt", "POST", 1),
    ("/v1/notebooks/{notebook_id}/environment/requirements.txt/preview", "POST", 1),
    ("/v1/notebooks/{notebook_id}/environment/sync", "POST", 1),
    ("/v1/notebooks/{notebook_id}/export", "GET", 1),
    ("/v1/notebooks/{notebook_id}/mounts", "PUT", 1),
    ("/v1/notebooks/{notebook_id}/name", "PUT", 1),
    ("/v1/notebooks/{notebook_id}/python-version", "PUT", 1),
    ("/v1/notebooks/{notebook_id}/quiesce", "POST", 1),
    ("/v1/notebooks/{notebook_id}/r-packages", "GET", 1),
    ("/v1/notebooks/{notebook_id}/release", "POST", 1),
    ("/v1/notebooks/{notebook_id}/secret-manager/config", "PUT", 1),
    ("/v1/notebooks/{notebook_id}/secret-manager/refresh", "POST", 1),
    ("/v1/notebooks/{notebook_id}/timeout", "PUT", 1),
    ("/v1/notebooks/{notebook_id}/variant-groups/{group_id}", "PUT", 1),
    ("/v1/notebooks/{notebook_id}/variant-groups/{group_id}/variants", "POST", 1),
    ("/v1/notebooks/{notebook_id}/worker", "PUT", 1),
    ("/v1/notebooks/{notebook_id}/workers", "GET", 1),
    ("/v1/notebooks/{notebook_id}/workers", "PUT", 1),
    ("/v1/notebooks/{notebook_id}/workers/ssh", "GET", 1),
    ("/v1/notebooks/{notebook_id}/workers/ssh", "POST", 1),
    ("/v1/notebooks/{notebook_id}/workers/ssh/{worker_name}", "DELETE", 1),
    ("/v1/projects/{path:path}/quiesce", "POST", 1),
    ("/v1/projects/{path:path}/release", "POST", 1),
    ("/v1/publications", "GET", 0),
    ("/v1/publications/{token}", "DELETE", 1),
    ("/v1/publications/{token}", "GET", 0),
    ("/v1/publications/{token}", "PATCH", 1),
    ("/v1/registry/artifacts", "GET", 0),
    ("/v1/registry/audit", "GET", 0),
    ("/v1/registry/pending", "GET", 0),
    ("/v1/registry/pending/approve", "POST", 0),
    ("/v1/registry/pending/reject", "POST", 0),
    ("/v1/registry/summary", "GET", 0),
    ("/v1/streams/{stream_id}", "GET", 0),
]


def _current_routes():
    # iter_route_contexts, not app.routes: since FastAPI 0.141 an included router is
    # one entry in app.routes, and its routes (with their include-time dependencies)
    # are only reachable through their contexts.
    return sorted(
        (route.path, ",".join(sorted(route.methods)), len(route.dependencies))
        for route in iter_route_contexts(app.routes)
        if isinstance(route.original_route, APIRoute) and route.path not in _EXCLUDED_PATHS
    )


def test_route_table_snapshot():
    """A mismatch means a route was added, removed, renamed, re-methoded or lost a gate."""
    assert _current_routes() == [tuple(row) for row in EXPECTED_ROUTES]
