// Generated by scripts/generate_ws_types.py -- do not edit.
//
// Source of truth: strata.notebook.ws_payloads. Regenerate with
//   uv run python scripts/generate_ws_types.py
// CI fails if this file is out of date with the models.

export interface CascadeProgressPayload {
  plan_id: string
  current_cell_id: string
  completed: number
  total: number
}

export interface CascadePromptPayload {
  cell_id: string
  plan_id: string
  cells_to_run: string[]
  estimated_duration_ms: number
}

export interface CascadeStepModel {
  cell_id: string
  cell_name: string
  reason: string
  skip: boolean
  estimated_ms: number
}

export interface CellAnalysisModel {
  id: string
  defines: string[]
  references: string[]
  upstream_ids: string[]
  downstream_ids: string[]
  is_leaf: boolean
  annotation_diagnostics: Record<string, unknown>[]
  variant_group?: string | null
  variant_name?: string | null
  variant_active?: boolean | null
  is_module_cell: boolean
  module_exports?: ModuleExportModel[] | null
}

export interface CellConsolePayload {
  cell_id: string
  stream: 'stdout' | 'stderr'
  text: string
}

export interface CellIterationProgressPayload {
  cell_id: string
  iteration: number
  max_iter: number
  artifact_uri?: string | null
  content_type?: string | null
  until_reached: boolean
  duration_ms: number
}

export interface CellOutputDeltaPayload {
  cell_id: string
  attempt: number
  kind: 'delta' | 'retry' | 'notice'
  text: string
}

export interface CellProfileModel {
  cell_id: string
  cell_name: string
  status: string
  duration_ms: number
  cache_hit: boolean
  artifact_uri?: string | null
  execution_count: number
}

export interface CellStatusPayload {
  cell_id: string
  status: string
  remote_worker?: string | null
  remote_transport?: string | null
  staleness_reasons?: string[] | null
  causality?: Record<string, unknown> | null
}

export interface CellTestCase {
  /** Test function name (pytest nodeid tail) */
  name: string
  /** Full pytest nodeid */
  nodeid: string
  /** passed | failed | error | skipped */
  outcome: 'passed' | 'failed' | 'error' | 'skipped'
  /** Failure/error message (the rewritten-assert diff for fails) */
  message: string
}

export interface CellTestResultsPayload {
  cell_id: string
  passed: number
  failed: number
  errored: number
  skipped: number
  tests: CellTestCase[]
  stale: boolean
  pytest_unavailable: boolean
  ran_at: number
  auto_installed: string[]
}

export interface CellTestStatusPayload {
  cell_id: string
  status: 'running' | 'ready' | 'error'
}

export interface CellVariantProgressPayload {
  cell_id: string
  variant: string
  index: number
  total: number
  success: boolean
  duration_ms: number
  error?: string | null
}

export interface DagEdgeModel {
  from_cell_id: string
  to_cell_id: string
  variable: string
}

export interface DagUpdatePayload {
  edges: DagEdgeModel[]
  roots: string[]
  leaves: string[]
  topological_order: string[]
  cells: CellAnalysisModel[]
  variant_groups: Record<string, unknown>[]
}

export interface DownstreamImpactModel {
  cell_id: string
  cell_name: string
  current_status: string
  new_status: string
}

export interface EnvironmentJobEventPayload {
  environment_job: EnvironmentJobModel
}

export interface EnvironmentJobModel {
  id: string
  action: string
  command: string
  status: string
  started_at: number
  package?: string | null
  phase?: string | null
  duration_ms?: number | null
  stdout: string
  stderr: string
  stdout_truncated: boolean
  stderr_truncated: boolean
  finished_at?: number | null
  lockfile_changed: boolean
  stale_cell_count: number
  stale_cell_ids: string[]
  error?: string | null
}

export interface ErrorPayload {
  error: string
  code?: 'ENVIRONMENT_BUSY' | 'cell_busy' | 'read_only' | 'insufficient_scope' | null
  cell_id?: string | null
}

export interface ImpactPreviewPayload {
  target_cell_id: string
  upstream: CascadeStepModel[]
  downstream: DownstreamImpactModel[]
  estimated_ms: number
}

export interface ModuleExportModel {
  name: string
  kind: string
}

export interface ProfilingSummaryPayload {
  total_execution_ms: number
  cache_hits: number
  cache_misses: number
  cache_savings_ms: number
  team_cache_savings_ms: number
  team_cache_hits: number
  team_contributors: string[]
  total_artifact_bytes: number
  cell_profiles: CellProfileModel[]
}

/** Frames whose payload shape is generated. Anything absent stays `unknown`. */
export interface WsServerPayloadMap {
  cascade_progress: CascadeProgressPayload
  cascade_prompt: CascadePromptPayload
  cell_console: CellConsolePayload
  cell_iteration_progress: CellIterationProgressPayload
  cell_output_delta: CellOutputDeltaPayload
  cell_status: CellStatusPayload
  cell_test_results: CellTestResultsPayload
  cell_test_status: CellTestStatusPayload
  cell_variant_progress: CellVariantProgressPayload
  dag_update: DagUpdatePayload
  environment_job_progress: EnvironmentJobEventPayload
  environment_job_started: EnvironmentJobEventPayload
  error: ErrorPayload
  impact_preview: ImpactPreviewPayload
  profiling_summary: ProfilingSummaryPayload
}

export type TypedWsFrame = keyof WsServerPayloadMap
