"""Move an existing SQLite artifact store onto Postgres.

Setting ``artifact_metadata_dsn`` starts an *empty* store: the schema is
created on first connection and nothing is carried over. That is fine for a
new deployment and useless for one that already has artifacts, so this copies
the metadata across.

Scope, stated up front:

- **Metadata only.** Blobs live in the blob store, which is configured
  separately, and a deployment moving to a shared database needs a shared blob
  backend anyway (service mode refuses the combination). Copying bytes is a
  different job with different failure modes -- see :func:`plan_migration`,
  which reports what the blobs are so the operator can act on it.
- **Ephemeral tables are skipped.** ``stream_owners`` records which node is
  serving a live stream right now; carrying those rows to a new database would
  advertise nodes for streams that no longer exist.

The copy is ordered, idempotent, and refuses to guess. Ordered because
``artifact_builds`` and ``artifact_names`` carry foreign keys into
``artifact_versions``, which Postgres enforces and SQLite never did.
Idempotent because a migration that dies halfway must be safe to re-run.
Refuses to guess because silently merging into a populated target is how two
deployments become one corrupted one.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field

from strata.sql_backend import SqlDialect, StoreConnection

logger = logging.getLogger(__name__)

# Tables whose primary key is generated by the backend. After a migration
# inserts explicit values into one, its generator has to be moved past them.
_AUTOINCREMENT_COLUMNS: dict[str, str] = {"registry_audit": "seq"}

# Ordered by foreign-key dependency: artifact_versions must exist before the
# tables that reference it. SQLite never enforced these (Strata does not enable
# PRAGMA foreign_keys) but Postgres does, so the order is load-bearing now.
#
# stream_owners is deliberately absent: it describes live streams on live
# nodes, and none of those survive the migration.
#
# Each entry pairs a table with its primary key, which is what makes the copy
# idempotent -- a row already present in the target is skipped, not rewritten.
MIGRATED_TABLES: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("artifact_versions", ("id", "version")),
    ("artifact_names", ("tenant", "name")),
    ("artifact_aliases", ("tenant", "name", "alias")),
    ("artifact_tags", ("tenant", "artifact_id", "version", "key")),
    ("registry_audit", ("seq",)),
    ("registry_pending", ("tenant", "name", "alias")),
    ("artifact_builds", ("build_id",)),
    ("api_keys", ("key_id",)),
)

# Rows fetched from the source per round, and per commit on the target.
_BATCH_ROWS = 500

# Named savepoint wrapping each row insert, so one rejected row cannot undo
# the batch around it.
_ROW_SAVEPOINT = "strata_migrate_row"


@dataclass
class MigrationPlan:
    """What a migration would move, gathered before anything is written."""

    source_counts: dict[str, int] = field(default_factory=dict)
    target_counts: dict[str, int] = field(default_factory=dict)
    missing_in_target: list[str] = field(default_factory=list)

    @property
    def total_rows(self) -> int:
        return sum(self.source_counts.values())

    @property
    def target_is_empty(self) -> bool:
        return all(count == 0 for count in self.target_counts.values())

    @property
    def blocking_tables(self) -> list[str]:
        """Missing target tables that actually have rows waiting for them.

        Not every table in ``MIGRATED_TABLES`` exists in every deployment:
        ``api_keys`` is created only under ``auth_mode='api_key'`` and
        ``artifact_builds`` only when the build store is constructed. A target
        booted the documented way legitimately lacks both, and refusing on
        that made the documented flow exit non-zero every time.

        A table missing from the target only matters when the source has rows
        that need somewhere to go.
        """
        return [table for table in self.missing_in_target if self.source_counts.get(table, 0) > 0]


@dataclass
class MigrationResult:
    """What a migration actually moved."""

    copied: dict[str, int] = field(default_factory=dict)
    skipped: dict[str, int] = field(default_factory=dict)
    # Rows the target refused, as (table, key, reason). Expected rather than
    # exceptional: a real store accumulates build rows whose artifact_versions
    # row was deleted by garbage_collect or delete_artifact, and Postgres
    # enforces the foreign key that SQLite never did.
    rejected: list[tuple[str, str, str]] = field(default_factory=list)

    @property
    def total_copied(self) -> int:
        return sum(self.copied.values())

    @property
    def total_skipped(self) -> int:
        return sum(self.skipped.values())

    @property
    def total_rejected(self) -> int:
        return len(self.rejected)


def _table_exists(dialect: SqlDialect, conn: StoreConnection, table: str) -> bool:
    return dialect.schema_exists(conn, table)


def _count(conn: StoreConnection, table: str) -> int:
    row = conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()  # noqa: S608 - fixed names
    return int(row[0]) if row else 0


def plan_migration(source: SqlDialect, target: SqlDialect) -> MigrationPlan:
    """Inspect both stores without writing anything.

    Run before migrating so the operator sees the size of the job and whether
    the target is already populated.
    """
    plan = MigrationPlan()

    src_conn = source.connect()
    try:
        for table, _ in MIGRATED_TABLES:
            if _table_exists(source, src_conn, table):
                plan.source_counts[table] = _count(src_conn, table)
            else:
                # A store predating a feature simply lacks its table; that is
                # not an error, there is just nothing to copy.
                plan.source_counts[table] = 0
    finally:
        src_conn.close()

    tgt_conn = target.connect()
    try:
        for table, _ in MIGRATED_TABLES:
            if _table_exists(target, tgt_conn, table):
                plan.target_counts[table] = _count(tgt_conn, table)
            else:
                plan.target_counts[table] = 0
                plan.missing_in_target.append(table)
    finally:
        tgt_conn.close()

    return plan


def migrate(
    source: SqlDialect,
    target: SqlDialect,
    *,
    allow_nonempty_target: bool = False,
) -> MigrationResult:
    """Copy metadata from ``source`` into ``target``.

    Parameters
    ----------
    allow_nonempty_target
        Permit writing into a target that already holds rows. Off by default:
        merging two stores silently is how a mistake becomes unrecoverable,
        and re-running an interrupted migration is the only legitimate reason
        to want it -- which is why the copy is idempotent.

    Notes
    -----
    Rows already present in the target are skipped rather than overwritten, so
    a migration interrupted halfway can simply be run again. Skipping (rather
    than upserting) is the safer default: if a row exists in both stores with
    different contents, the target has been written to since the migration
    began, and clobbering it would discard newer work.
    """
    plan = plan_migration(source, target)

    # Up front, before anything is written. Discovering this mid-loop leaves
    # the earlier tables copied and committed, so the retry then needs
    # allow_nonempty_target for a mistake the caller never made.
    if plan.blocking_tables:
        raise ValueError(
            f"target is missing {plan.blocking_tables}, which the source has rows for. "
            "Start Strata against the target database once so it creates the schema, "
            "then migrate."
        )

    if not plan.target_is_empty and not allow_nonempty_target:
        populated = {t: n for t, n in plan.target_counts.items() if n}
        raise ValueError(
            f"target already holds rows in {populated}. Re-running an interrupted "
            "migration is safe -- pass allow_nonempty_target=True -- but merging two "
            "different stores is not, so this refuses by default."
        )

    result = MigrationResult()
    src_conn = source.connect()
    tgt_conn = None
    try:
        # Opened inside the try: if this raises -- Postgres unreachable, pool
        # timeout -- the source connection above still has to be closed.
        tgt_conn = target.connect()
        for table, key_columns in MIGRATED_TABLES:
            if not _table_exists(source, src_conn, table) or plan.source_counts[table] == 0:
                result.copied[table] = 0
                result.skipped[table] = 0
                continue
            copied, skipped = _copy_table(src_conn, tgt_conn, table, key_columns, target, result)
            result.copied[table] = copied
            result.skipped[table] = skipped

            # The rows carried their own primary keys, so a backend-generated
            # key would otherwise start over at 1 and collide on the first
            # write after the migration.
            #
            # Not gated on `copied`: a run killed between the last batch commit
            # and this line leaves the rows in place with the sequence still at
            # 1, and the resumed run copies nothing, so gating here would skip
            # the resync forever and reintroduce exactly the collision it
            # exists to prevent. setval to MAX+1 is idempotent.
            autoincrement_column = _AUTOINCREMENT_COLUMNS.get(table)
            if autoincrement_column is not None:
                target.resync_autoincrement(tgt_conn, table, autoincrement_column)
                tgt_conn.commit()

            logger.info("migrated_table", extra={"table": table, "copied": copied})
    finally:
        src_conn.close()
        if tgt_conn is not None:
            tgt_conn.close()

    return result


def _copy_table(
    src_conn: StoreConnection,
    tgt_conn: StoreConnection,
    table: str,
    key_columns: tuple[str, ...],
    target: SqlDialect,
    result: MigrationResult,
) -> tuple[int, int]:
    """Copy one table, skipping rows the target already has.

    Streams the source with ``fetchmany`` rather than reading it whole: a
    multi-million-row ``artifact_versions`` would otherwise be materialized
    entirely in memory before a single row moved.

    The target's existing keys are read once into a set instead of being
    probed per row. The probe version cost a network round trip for every row
    on top of its insert, which on a fresh target is one wasted query per row
    of the whole store. On a fresh target that set is empty and is not read at
    all; on a resumed run it holds one tuple per already-copied row, which is
    the honest cost of making the copy idempotent without a per-row probe.

    Returns ``(copied, skipped)``; rows the target refuses are recorded on
    ``result.rejected`` and do not abort the run.
    """
    # Only on a resume: a fresh target has nothing to skip against, and
    # reading an empty table's keys is a query for a set we know is empty.
    existing_keys = (
        _existing_keys(tgt_conn, table, key_columns) if _count(tgt_conn, table) else set()
    )

    cursor = src_conn.execute(f"SELECT * FROM {table}")  # noqa: S608 - fixed names
    copied = 0
    skipped = 0
    columns: tuple[str, ...] | None = None
    statement = ""

    while True:
        rows = cursor.fetchmany(_BATCH_ROWS)
        if not rows:
            break
        if columns is None:
            columns = tuple(rows[0].keys())
            placeholders = ", ".join("?" for _ in columns)
            statement = f"INSERT INTO {table} ({', '.join(columns)}) VALUES ({placeholders})"  # noqa: S608

        for row in rows:
            key = tuple(row[c] for c in key_columns)
            if key in existing_keys:
                skipped += 1
                continue

            # One savepoint per row. Without it, a rejected row rolls back the
            # whole uncommitted batch -- every good row inserted since the last
            # commit -- while `copied` has already counted them, so the run
            # reports success having silently dropped up to _BATCH_ROWS rows.
            # Measured at 99 lost out of 100 before this.
            tgt_conn.execute(f"SAVEPOINT {_ROW_SAVEPOINT}")
            try:
                tgt_conn.execute(statement, tuple(row[c] for c in columns))
            except target.rejectable_errors as exc:
                # A constraint or a value the source never enforced. Undo just
                # this row and keep going: aborting would strand the migration
                # partway through with everything before it committed.
                tgt_conn.execute(f"ROLLBACK TO SAVEPOINT {_ROW_SAVEPOINT}")
                result.rejected.append((table, repr(key), str(exc).strip().splitlines()[0]))
            else:
                copied += 1
            tgt_conn.execute(f"RELEASE SAVEPOINT {_ROW_SAVEPOINT}")
        tgt_conn.commit()

    return copied, skipped


def _existing_keys(conn: StoreConnection, table: str, key_columns: tuple[str, ...]) -> set[tuple]:
    """Primary keys already in the target, read in one query."""
    cursor = conn.execute(
        f"SELECT {', '.join(key_columns)} FROM {table}"  # noqa: S608 - fixed names
    )
    return {tuple(row[c] for c in key_columns) for row in cursor.fetchall()}
