"""Move an existing SQLite artifact store onto Postgres.

Setting ``artifact_metadata_dsn`` starts an *empty* store: the schema is
created on first connection and nothing is carried over. That is fine for a
new deployment and useless for one that already has artifacts, so this copies
the metadata across.

Scope, stated up front:

- **Metadata only.** Blobs live in the blob store, which is configured
  separately, and a deployment moving to a shared database needs a shared blob
  backend anyway (service mode refuses the combination). Copying bytes is a
  different job with different failure modes -- see :func:`plan_migration`,
  which reports what the blobs are so the operator can act on it.
- **Ephemeral tables are skipped.** ``stream_owners`` records which node is
  serving a live stream right now; carrying those rows to a new database would
  advertise nodes for streams that no longer exist.

The copy is ordered, idempotent, and refuses to guess. Ordered because
``artifact_builds`` and ``artifact_names`` carry foreign keys into
``artifact_versions``, which Postgres enforces and SQLite never did.
Idempotent because a migration that dies halfway must be safe to re-run.
Refuses to guess because silently merging into a populated target is how two
deployments become one corrupted one.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field

from strata.sql_backend import SqlDialect, StoreConnection

logger = logging.getLogger(__name__)

# Tables whose primary key is generated by the backend. After a migration
# inserts explicit values into one, its generator has to be moved past them.
_AUTOINCREMENT_COLUMNS: dict[str, str] = {"registry_audit": "seq"}

# Ordered by foreign-key dependency: artifact_versions must exist before the
# tables that reference it. SQLite never enforced these (Strata does not enable
# PRAGMA foreign_keys) but Postgres does, so the order is load-bearing now.
#
# stream_owners is deliberately absent: it describes live streams on live
# nodes, and none of those survive the migration.
#
# Each entry pairs a table with its primary key, which is what makes the copy
# idempotent -- a row already present in the target is skipped, not rewritten.
MIGRATED_TABLES: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("artifact_versions", ("id", "version")),
    ("artifact_names", ("tenant", "name")),
    ("artifact_aliases", ("tenant", "name", "alias")),
    ("artifact_tags", ("tenant", "artifact_id", "version", "key")),
    ("registry_audit", ("seq",)),
    ("registry_pending", ("tenant", "name", "alias")),
    ("artifact_builds", ("build_id",)),
    ("api_keys", ("key_id",)),
)

# Copied in batches so a large store does not have to fit in memory.
_BATCH_ROWS = 500


@dataclass
class MigrationPlan:
    """What a migration would move, gathered before anything is written."""

    source_counts: dict[str, int] = field(default_factory=dict)
    target_counts: dict[str, int] = field(default_factory=dict)
    missing_in_target: list[str] = field(default_factory=list)

    @property
    def total_rows(self) -> int:
        return sum(self.source_counts.values())

    @property
    def target_is_empty(self) -> bool:
        return all(count == 0 for count in self.target_counts.values())


@dataclass
class MigrationResult:
    """What a migration actually moved."""

    copied: dict[str, int] = field(default_factory=dict)
    skipped: dict[str, int] = field(default_factory=dict)

    @property
    def total_copied(self) -> int:
        return sum(self.copied.values())

    @property
    def total_skipped(self) -> int:
        return sum(self.skipped.values())


def _table_exists(dialect: SqlDialect, conn: StoreConnection, table: str) -> bool:
    return dialect.schema_exists(conn, table)


def _count(conn: StoreConnection, table: str) -> int:
    row = conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()  # noqa: S608 - fixed names
    return int(row[0]) if row else 0


def plan_migration(source: SqlDialect, target: SqlDialect) -> MigrationPlan:
    """Inspect both stores without writing anything.

    Run before migrating so the operator sees the size of the job and whether
    the target is already populated.
    """
    plan = MigrationPlan()

    src_conn = source.connect()
    try:
        for table, _ in MIGRATED_TABLES:
            if _table_exists(source, src_conn, table):
                plan.source_counts[table] = _count(src_conn, table)
            else:
                # A store predating a feature simply lacks its table; that is
                # not an error, there is just nothing to copy.
                plan.source_counts[table] = 0
    finally:
        src_conn.close()

    tgt_conn = target.connect()
    try:
        for table, _ in MIGRATED_TABLES:
            if _table_exists(target, tgt_conn, table):
                plan.target_counts[table] = _count(tgt_conn, table)
            else:
                plan.target_counts[table] = 0
                plan.missing_in_target.append(table)
    finally:
        tgt_conn.close()

    return plan


def migrate(
    source: SqlDialect,
    target: SqlDialect,
    *,
    allow_nonempty_target: bool = False,
) -> MigrationResult:
    """Copy metadata from ``source`` into ``target``.

    Parameters
    ----------
    allow_nonempty_target
        Permit writing into a target that already holds rows. Off by default:
        merging two stores silently is how a mistake becomes unrecoverable,
        and re-running an interrupted migration is the only legitimate reason
        to want it -- which is why the copy is idempotent.

    Notes
    -----
    Rows already present in the target are skipped rather than overwritten, so
    a migration interrupted halfway can simply be run again. Skipping (rather
    than upserting) is the safer default: if a row exists in both stores with
    different contents, the target has been written to since the migration
    began, and clobbering it would discard newer work.
    """
    plan = plan_migration(source, target)
    if not plan.target_is_empty and not allow_nonempty_target:
        populated = {t: n for t, n in plan.target_counts.items() if n}
        raise ValueError(
            f"target already holds rows in {populated}. Re-running an interrupted "
            "migration is safe -- pass allow_nonempty_target=True -- but merging two "
            "different stores is not, so this refuses by default."
        )

    result = MigrationResult()
    src_conn = source.connect()
    tgt_conn = target.connect()
    try:
        for table, key_columns in MIGRATED_TABLES:
            if not _table_exists(source, src_conn, table) or plan.source_counts[table] == 0:
                result.copied[table] = 0
                result.skipped[table] = 0
                continue
            if not _table_exists(target, tgt_conn, table):
                # The target schema is created by the stores themselves at
                # startup. A table missing here means the operator has not
                # booted against this database yet, and inventing the DDL from
                # a second place is how two definitions drift apart.
                raise ValueError(
                    f"target is missing table {table!r}. Start Strata against the "
                    "target database once so it creates the schema, then migrate."
                )

            copied, skipped = _copy_table(src_conn, tgt_conn, table, key_columns)
            result.copied[table] = copied
            result.skipped[table] = skipped

            # The rows carried their own primary keys, so a backend-generated
            # key would otherwise start over at 1 and collide on the first
            # write after the migration.
            autoincrement_column = _AUTOINCREMENT_COLUMNS.get(table)
            if copied and autoincrement_column is not None:
                target.resync_autoincrement(tgt_conn, table, autoincrement_column)
                tgt_conn.commit()

            logger.info("migrated_table", extra={"table": table, "copied": copied})
    finally:
        src_conn.close()
        tgt_conn.close()

    return result


def _copy_table(
    src_conn: StoreConnection,
    tgt_conn: StoreConnection,
    table: str,
    key_columns: tuple[str, ...],
) -> tuple[int, int]:
    """Copy one table, skipping rows the target already has.

    Returns ``(copied, skipped)``.
    """
    cursor = src_conn.execute(f"SELECT * FROM {table}")  # noqa: S608 - fixed names
    rows = cursor.fetchall()
    if not rows:
        return 0, 0

    columns = tuple(rows[0].keys())
    placeholders = ", ".join("?" for _ in columns)
    column_list = ", ".join(columns)
    where = " AND ".join(f"{c} = ?" for c in key_columns)

    copied = 0
    skipped = 0
    for start in range(0, len(rows), _BATCH_ROWS):
        for row in rows[start : start + _BATCH_ROWS]:
            key_values = tuple(row[c] for c in key_columns)
            existing = tgt_conn.execute(
                f"SELECT 1 FROM {table} WHERE {where}",  # noqa: S608 - fixed names
                key_values,
            ).fetchone()
            if existing is not None:
                skipped += 1
                continue

            tgt_conn.execute(
                f"INSERT INTO {table} ({column_list}) VALUES ({placeholders})",  # noqa: S608
                tuple(row[c] for c in columns),
            )
            copied += 1
        tgt_conn.commit()

    return copied, skipped
