"""Write a compiled pipeline to a deployable bundle directory.

Layout depends on ``ir.runtime``.

**container** (default — Python 3.12 Lambda image, exact notebook parity)::

    <out>/
      pipeline.json            # the Pipeline IR
      statemachine.asl.json    # Step Functions state machine (lambda:invoke)
      access.json              # data/model access + parity risks
      Dockerfile               # the node-runtime image
      handler.py, nodes.json   # Lambda entrypoint + baked node sources
      serializer.py, provenance.py, runtime.py   # vendored runtime kit
      README.md

**glue** (opt-in, ``--runtime glue``)::

    <out>/
      pipeline.json, statemachine.asl.json, access.json, requirements.txt
      glue/<node_id>.py        # one Glue Python Shell script per Python/SQL node
      README.md
"""

from __future__ import annotations

import json
from pathlib import Path

from strata.pipeline.access import build_access_manifest
from strata.pipeline.asl import AslRenderOptions, render_state_machine
from strata.pipeline.container import (
    build_nodes_manifest,
    render_dockerfile,
    render_handler,
    vendor_runtime_kit,
)
from strata.pipeline.glue import GLUE_TARGETS, render_glue_script
from strata.pipeline.ir import PipelineIR


def _readme(ir: PipelineIR) -> str:
    container = ir.runtime == "container"
    lines = [
        f"# {ir.pipeline_name} - compiled pipeline",
        "",
        f"Generated by `strata compile` from pipeline `{ir.pipeline_id}` "
        f"(target: {ir.target}, runtime: {ir.runtime}).",
        "",
        "## Contents",
        "",
        "- `pipeline.json` - the pipeline IR (nodes, edges, provenance preview)",
        "- `statemachine.asl.json` - AWS Step Functions state machine",
        "- `access.json` - data/model access the pipeline needs + parity risks",
    ]
    if container:
        lines += [
            "- `Dockerfile` - Python 3.12 node-runtime image (exact notebook parity)",
            "- `handler.py` + `nodes.json` - Lambda entrypoint + baked node sources",
            "- `serializer.py` / `provenance.py` / `runtime.py` - vendored runtime kit",
        ]
    else:
        lines += [
            "- `glue/<node>.py` - Glue Python Shell script per Python / SQL node",
            "- `requirements.txt` - Glue-job Python dependencies",
        ]
    lines += ["", "## Nodes", ""]
    for node in ir.nodes:
        lines.append(f"- `{node.id}` ({node.name}) -> {node.compute_target}")

    manifest = build_access_manifest(ir)
    if manifest.tables or manifest.mounts or manifest.connections:
        lines += ["", "## Data / model access (parity contract)", ""]
        for t in manifest.tables:
            pin = f"@{t.snapshot_pin}" if t.snapshot_pin is not None else " (unpinned)"
            lines.append(f"- table `{t.name}` {t.uri}{pin}")
        for m in manifest.mounts:
            lines.append(f"- mount `{m.name}` ({m.mode}) {m.uri}")
        for c in manifest.connections:
            lines.append(f"- connection `{c.name}` ({c.driver})")
    if manifest.required_env_vars:
        lines += ["", "## Required env / secrets", ""]
        lines += [f"- `{v}`" for v in manifest.required_env_vars]
    if manifest.parity_risks:
        lines += ["", "## Parity risks", ""]
        lines += [f"- {r}" for r in manifest.parity_risks]

    lines += ["", "## Deploy notes", ""]
    if container:
        lines += [
            "- Build + push the image, then create one Lambda from it and a "
            "Step Functions state machine from `statemachine.asl.json`:",
            "  1. `docker build -t <repo>:latest .` (arm64 or x86_64)",
            "  2. push to ECR; `aws lambda create-function --package-type Image ...`",
            "  3. set the ASL `FunctionName` to that Lambda; "
            "`aws stepfunctions create-state-machine ...`",
            "- Python 3.12 = exact notebook parity (no Glue 3.9 gap).",
            "- The Lambda role needs read/write on the artifact S3 bucket "
            "(see `access.json` for the data/model access to grant).",
        ]
    else:
        py = ir.requires_python or "unspecified"
        lines += [
            f"- Glue Python Shell runs **Python 3.9**; this notebook targets `{py}` - "
            "verify your dependencies ship 3.9 / manylinux wheels.",
            "- Install `requirements.txt` on each Glue job via "
            "`--additional-python-modules`, plus the `strata-notebook` runtime.",
            "- SQL nodes need their driver's ADBC package and reachable credentials "
            "(see `access.json` / required env).",
        ]

    if ir.parameters:
        lines += ["", "## Parameters (from widget cells)", ""]
        lines += [f"- `{p.name}` (from `{p.from_cell}`)" for p in ir.parameters]
    if ir.unsupported:
        lines += ["", "## Not compiled", ""]
        lines += [f"- `{u.id}` ({u.language}): {u.reason}" for u in ir.unsupported]
    if ir.warnings:
        lines += ["", "## Warnings", ""]
        lines += [f"- {w}" for w in ir.warnings]
    return "\n".join(lines) + "\n"


def _requirements_txt(ir: PipelineIR) -> str:
    """The Glue-job dependency manifest for the pipeline's Python/SQL nodes."""
    py = ir.requires_python or "unspecified"
    header = [
        f"# Generated by `strata compile` for pipeline {ir.pipeline_id}.",
        "# Install into each Glue Python Shell job via --additional-python-modules.",
        f"# Glue Python Shell runs Python 3.9 (notebook targets: {py});",
        "# use prebuilt manylinux wheels for compiled dependencies.",
        "# The generated node scripts also require the Strata runtime:",
        "strata-notebook",
    ]
    return "\n".join([*header, *ir.requirements]) + "\n"


def write_bundle(
    ir: PipelineIR, out_dir: Path | str, options: AslRenderOptions | None = None
) -> list[Path]:
    """Write the pipeline bundle for *ir* under *out_dir*; return files written."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    def write(name: str, content: str) -> None:
        path = out / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, "utf-8")
        written.append(path)

    write("pipeline.json", json.dumps(ir.model_dump(mode="json"), indent=2) + "\n")
    write(
        "statemachine.asl.json",
        json.dumps(render_state_machine(ir, options), indent=2) + "\n",
    )
    write(
        "access.json",
        json.dumps(build_access_manifest(ir).model_dump(mode="json"), indent=2) + "\n",
    )

    if ir.runtime == "container":
        write("Dockerfile", render_dockerfile(ir))
        write("handler.py", render_handler())
        write("nodes.json", json.dumps(build_nodes_manifest(ir), indent=2) + "\n")
        for filename, source in vendor_runtime_kit().items():
            write(filename, source)
    else:  # glue
        write("requirements.txt", _requirements_txt(ir))
        for node in (n for n in ir.nodes if n.compute_target in GLUE_TARGETS):
            write(f"glue/{node.id}.py", render_glue_script(node, env_hash=ir.env_hash))

    write("README.md", _readme(ir))
    return written
