"""Container (Lambda) runtime renderer — the validated production target.

Each node runs in a Python 3.12 image (exact parity with the notebook: same
Python, same libs, same ``serializer.py``), invoked per node by the Step
Functions state machine (``lambda:invoke``). The image bundles a vendored
runtime kit (``serializer.py`` + ``provenance.py`` copy as-is on 3.12;
``runtime.py`` with its imports rewritten to the flat layout) plus the node
sources (``nodes.json``), so it needs no Strata install.

This mirrors the manually-validated iris deploy (Glue was dropped because its
Python Shell runtime is hard-locked to 3.9).
"""

from __future__ import annotations

from pathlib import Path

from strata.pipeline.ir import PipelineIR

# Non-notebook deps the runtime kit itself needs (data libs come from the IR).
_KIT_DEPS = ("cloudpickle", "fsspec", "s3fs")


def build_nodes_manifest(ir: PipelineIR) -> dict:
    """The ``nodes.json`` baked into the image: {node_id: {source, env_hash}}."""
    return {n.id: {"source": n.source, "env_hash": ir.env_hash} for n in ir.nodes}


def container_requirements(ir: PipelineIR) -> list[str]:
    """Pip requirements for the image: notebook data deps + kit deps (no Strata).

    Strata is intentionally *not* installed — the runtime kit is vendored, so
    the image stays independent of a Strata release.
    """
    reqs = list(ir.requirements)
    present = {r.lower() for r in reqs}
    for dep in _KIT_DEPS:
        if not any(dep in p for p in present):
            reqs.append(dep)
    return reqs


def render_handler() -> str:
    """The Lambda handler: looks a node up by id and runs it through the kit."""
    return '''"""Auto-generated by `strata compile` — Lambda entrypoint for a pipeline node."""

import json
import os

from runtime import run_python_node

with open(os.path.join(os.path.dirname(__file__), "nodes.json"), encoding="utf-8") as _f:
    NODES = json.load(_f)


def handler(event, _context):
    node = NODES[event["node_id"]]
    result = run_python_node(
        source=node["source"],
        inputs=event.get("inputs", {}),
        outputs=event.get("outputs", {}),
        env_hash=node.get("env_hash", ""),
    )
    return {
        "node_id": event["node_id"],
        "skipped": result["skipped"],
        "provenance": result["provenance"],
    }
'''


def render_dockerfile(ir: PipelineIR) -> str:
    """Dockerfile for the Python 3.12 Lambda-container image."""
    pip = " \\\n      ".join(f'"{r}"' for r in container_requirements(ir))
    return f"""# Auto-generated by `strata compile`. Strata pipeline node runtime.
# Python 3.12 = exact parity with the notebook (Glue Python Shell is 3.9-locked).
FROM public.ecr.aws/lambda/python:3.12

ENV MPLCONFIGDIR=/tmp/mpl

RUN pip install --no-cache-dir \\
      {pip}

# Vendored runtime kit (serializer/provenance are 3.12-native) + handler + node sources.
COPY serializer.py provenance.py runtime.py handler.py nodes.json ${{LAMBDA_TASK_ROOT}}/

CMD ["handler.handler"]
"""


def vendor_runtime_kit() -> dict[str, str]:
    """Return {filename: source} for the vendored kit, imports flattened.

    Reads the live Strata modules so the vendored code is exactly what the
    notebook uses; only ``runtime.py``'s two package imports are rewritten to
    the flat (installed-side-by-side) layout the image uses.
    """
    from strata.notebook import provenance as _prov
    from strata.notebook import serializer as _ser
    from strata.pipeline import runtime as _rt

    runtime_src = (
        Path(_rt.__file__)
        .read_text(encoding="utf-8")
        .replace("from strata.notebook.provenance import", "from provenance import")
        .replace("from strata.notebook.serializer import", "from serializer import")
    )
    return {
        "serializer.py": Path(_ser.__file__).read_text(encoding="utf-8"),
        "provenance.py": Path(_prov.__file__).read_text(encoding="utf-8"),
        "runtime.py": runtime_src,
    }
