"""Render a Python pipeline node into an AWS Glue Python Shell script.

The emitted script is a thin entrypoint: it reads the Glue job arguments
(``--strata_inputs`` / ``--strata_outputs`` as JSON ``{variable: uri}`` maps),
then hands the cell body to :func:`strata.pipeline.runtime.run_python_node`.
Keeping the logic in the imported runtime (rather than inlining it) means the
generated file stays tiny and the behavior is unit-tested directly, not through
a stringly-generated script.

The runtime is imported from ``strata`` — the compiled pipeline depends on
Strata at run time by design (provenance-aware handoff), so the Glue job needs
Strata installed (P4 packages the wheel).
"""

from __future__ import annotations

import json

from strata.pipeline.ir import PipelineNode

_GLUE_ARGS = ["strata_node", "strata_inputs", "strata_outputs"]
GLUE_TARGETS = ("glue_python_shell", "glue_sql")


def render_glue_script(node: PipelineNode, *, env_hash: str = "") -> str:
    """Return the Glue Python Shell script source for a *node*.

    Python nodes call ``run_python_node``; SQL nodes (``glue_sql``) call
    ``run_sql_node`` against their own connection engine (parity). ``env_hash``
    is folded into each node's runtime provenance so the skip check invalidates
    on an environment change.

    Raises
    ------
    ValueError
        If *node* is not a Glue node.
    """
    if node.compute_target not in GLUE_TARGETS:
        raise ValueError(f"node {node.id!r} is not a Glue node ({node.compute_target})")

    # json.dumps produces valid Python literals for the embedded values,
    # safely escaping quotes/newlines without f-string interpolation hazards.
    source_literal = json.dumps(node.source)
    env_literal = json.dumps(node.env)
    env_hash_literal = json.dumps(env_hash)
    args_literal = json.dumps(_GLUE_ARGS)
    header = (
        f'"""Auto-generated by `strata compile` - Glue node {node.id!r}.\n\n'
        'Do not edit by hand; regenerate with `strata compile --emit bundle`.\n"""'
    )
    preamble = f"""{header}

import json
import sys

from awsglue.utils import getResolvedOptions

SOURCE = {source_literal}
ENV = {env_literal}
ENV_HASH = {env_hash_literal}

_args = getResolvedOptions(sys.argv, {args_literal})
"""

    if node.compute_target == "glue_sql":
        config_literal = json.dumps(node.connection_config or {})
        return f"""{preamble}
from strata.pipeline.runtime import run_sql_node

run_sql_node(
    source=SOURCE,
    connection_config={config_literal},
    inputs=json.loads(_args["strata_inputs"]),
    outputs=json.loads(_args["strata_outputs"]),
    env=ENV or None,
    env_hash=ENV_HASH,
)
"""

    return f"""{preamble}
from strata.pipeline.runtime import run_python_node

run_python_node(
    source=SOURCE,
    inputs=json.loads(_args["strata_inputs"]),
    outputs=json.loads(_args["strata_outputs"]),
    env=ENV or None,
    env_hash=ENV_HASH,
)
"""
