"""Generate TypeScript payload types for the notebook WS protocol.

``frontend/src/types/notebook.ts`` types ``WsMessage.payload`` as ``unknown``,
so every consumer casts and the shapes live only at the Python emit sites. The
payload models exist now (``strata.notebook.ws_payloads``); this turns them into
declarations the frontend can narrow on, from the one source.

Run it after changing a payload model::

    uv run python scripts/generate_ws_types.py

``--check`` re-renders and diffs instead of writing, which is what CI does: the
generated file is committed, so a model change that skips regeneration fails
rather than letting the two definitions drift apart quietly.

The emitter handles exactly the JSON Schema constructs these models produce and
raises on anything else. Emitting ``any`` for an unrecognised shape would defeat
the point -- the frontend would compile against a type that promises nothing.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

_REPO = Path(__file__).resolve().parent.parent
_OUT = _REPO / "frontend" / "src" / "types" / "ws-payloads.generated.ts"

_HEADER = """// Generated by scripts/generate_ws_types.py -- do not edit.
//
// Source of truth: strata.notebook.ws_payloads. Regenerate with
//   uv run python scripts/generate_ws_types.py
// CI fails if this file is out of date with the models."""


class UnsupportedSchema(RuntimeError):
    """A construct the emitter does not know how to render."""


def _ts_type(schema: dict[str, Any], required: bool) -> str:
    """Render one JSON Schema node as a TypeScript type."""
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]

    if "anyOf" in schema:
        parts = [_ts_type(s, True) for s in schema["anyOf"]]
        # Optionals arrive as anyOf[T, null]; "| null" is kept rather than
        # folded into "?" because the wire really can carry an explicit null,
        # and a consumer that only checks for absence would miss it.
        return " | ".join(dict.fromkeys(parts))

    if "enum" in schema:
        return " | ".join(f"'{v}'" for v in schema["enum"])

    kind = schema.get("type")
    if kind == "string":
        return "string"
    if kind in ("integer", "number"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array":
        return f"{_ts_type(schema.get('items', {}), True)}[]"
    if kind == "object":
        # A free-form mapping (dict[str, Any] passthrough fields).
        return "Record<string, unknown>"
    if not schema:
        return "unknown"
    raise UnsupportedSchema(f"cannot render {schema!r}")


def _interface(name: str, schema: dict[str, Any]) -> str:
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]
    for field, spec in schema.get("properties", {}).items():
        optional = "" if field in required else "?"
        doc = spec.get("description")
        if doc:
            lines.append(f"  /** {' '.join(doc.split())} */")
        lines.append(f"  {field}{optional}: {_ts_type(spec, field in required)}")
    lines.append("}")
    return "\n".join(lines)


def render() -> str:
    from strata.notebook.ws_payloads import FRAME_PAYLOADS

    defs: dict[str, dict[str, Any]] = {}
    roots: dict[str, str] = {}
    for frame, model in sorted(FRAME_PAYLOADS.items(), key=lambda kv: kv[0].value):
        schema = model.model_json_schema()
        for dep_name, dep in schema.pop("$defs", {}).items():
            defs[dep_name] = dep
        defs[model.__name__] = schema
        roots[frame.value] = model.__name__

    blocks = [_HEADER]
    for name in sorted(defs):
        blocks.append(_interface(name, defs[name]))

    entries = "\n".join(f"  {frame}: {model}" for frame, model in sorted(roots.items()))
    blocks.append(
        "/** Frames whose payload shape is generated. Anything absent stays `unknown`. */\n"
        f"export interface WsServerPayloadMap {{\n{entries}\n}}"
    )
    blocks.append("export type TypedWsFrame = keyof WsServerPayloadMap")
    return "\n\n".join(blocks) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="diff instead of writing")
    args = parser.parse_args()

    rendered = render()
    if not args.check:
        _OUT.parent.mkdir(parents=True, exist_ok=True)
        _OUT.write_text(rendered, encoding="utf-8")
        print(f"wrote {_OUT.relative_to(_REPO)}")
        return 0

    current = _OUT.read_text(encoding="utf-8") if _OUT.exists() else ""
    if current == rendered:
        print("ws-payloads.generated.ts is up to date")
        return 0
    print(
        f"{_OUT.relative_to(_REPO)} is stale.\nRun: uv run python scripts/generate_ws_types.py",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
