"""Generate TypeScript payload types for the notebook WS protocol.

Renders the ``strata.notebook.ws_payloads`` models as declarations the frontend
can narrow on. Run it after changing a payload model::

    uv run python scripts/generate_ws_types.py

``--check`` diffs instead of writing; CI runs it so the committed file cannot
drift from the models. Unknown JSON Schema constructs raise rather than emit
``any``, a type that would promise nothing.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

_REPO = Path(__file__).resolve().parent.parent
_OUT = _REPO / "frontend" / "src" / "types" / "ws-payloads.generated.ts"

_HEADER = """// Generated by scripts/generate_ws_types.py -- do not edit.
//
// Source of truth: strata.notebook.ws_payloads. Regenerate with
//   uv run python scripts/generate_ws_types.py
// CI fails if this file is out of date with the models."""


class UnsupportedSchema(RuntimeError):
    """A construct the emitter does not know how to render."""


def _ts_literal(value: object) -> str:
    """Render one enum / const member as a TypeScript literal.

    Typed by the member, not stringified: an ``IntEnum`` sends ``1``, and
    ``'1'`` would be a union that can never match. Strings are escaped so a
    quote or backslash cannot produce invalid TypeScript.
    """
    if isinstance(value, bool):
        # Before int: bool is a subclass of it.
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if value is None:
        return "null"
    if isinstance(value, str):
        return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"
    raise UnsupportedSchema(f"cannot render literal {value!r}")


def _ts_type(schema: dict[str, Any]) -> str:
    """Render one JSON Schema node as a TypeScript type."""
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]

    if "anyOf" in schema:
        parts = [_ts_type(s) for s in schema["anyOf"]]
        # Keep "| null" rather than folding it into "?": the wire can carry an
        # explicit null.
        return " | ".join(dict.fromkeys(parts))

    if "enum" in schema:
        return " | ".join(_ts_literal(v) for v in schema["enum"])

    if "const" in schema:
        # A single-member Literal has ``const`` but no ``enum``; without this it
        # would fall through to its base type.
        return _ts_literal(schema["const"])

    kind = schema.get("type")
    if kind == "string":
        return "string"
    if kind in ("integer", "number"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array":
        # No ``items`` means a tuple (``prefixItems``) or something unmodelled;
        # ``unknown[]`` would describe nothing, so refuse.
        if "items" not in schema:
            raise UnsupportedSchema(f"array without items: {schema!r}")
        return f"{_ts_type(schema['items'])}[]"
    if kind == "object":
        # A free-form mapping (dict[str, Any] passthrough fields).
        return "Record<string, unknown>"
    if schema == {}:
        # Bare ``Any``; a node the emitter does not understand raises below.
        return "unknown"
    raise UnsupportedSchema(f"cannot render {schema!r}")


def _is_optional(spec: dict[str, Any]) -> bool:
    """Whether a field can actually be absent from the wire dict.

    Nullability, not JSON Schema's ``required``: ``model_dump`` still emits
    defaulted fields, and only ``exclude_none`` drops keys (those holding
    ``None``).
    """
    return any(part.get("type") == "null" for part in spec.get("anyOf", []))


def _doc_comment(text: str) -> str:
    # An unescaped ``*/`` would close the comment early and break the file.
    return f"  /** {' '.join(text.split()).replace('*/', '*\\/')} */"


# The frontend's prettier ``printWidth``; a longer line would be rewritten by
# prettier and then flagged as drift by ``--check``.
_PRINT_WIDTH = 100


def _field_line(field: str, optional: str, ts: str) -> str:
    """One interface member, wrapped the way prettier wraps it when too long."""
    line = f"  {field}{optional}: {ts}"
    if len(line) <= _PRINT_WIDTH:
        return line
    if len(f"    {ts}") <= _PRINT_WIDTH:
        return f"  {field}{optional}:\n    {ts}"
    members = "\n".join(f"    | {part}" for part in ts.split(" | "))
    return f"  {field}{optional}:\n{members}"


def _interface(name: str, schema: dict[str, Any]) -> str:
    if "enum" in schema:
        # A Python Enum is a bare enum node; as an interface it would be ``{}``,
        # which accepts almost anything.
        return f"export type {name} = {_ts_type(schema)}"
    if "properties" not in schema:
        raise UnsupportedSchema(f"{name}: not an object or enum: {schema!r}")
    lines = [f"export interface {name} {{"]
    for field, spec in schema.get("properties", {}).items():
        optional = "?" if _is_optional(spec) else ""
        doc = spec.get("description")
        if doc:
            lines.append(_doc_comment(doc))
        lines.append(_field_line(field, optional, _ts_type(spec)))
    lines.append("}")
    return "\n".join(lines)


def render() -> str:
    from strata.notebook.ws_payloads import FRAME_PAYLOADS

    defs: dict[str, dict[str, Any]] = {}
    roots: dict[str, str] = {}
    for frame, model in sorted(FRAME_PAYLOADS.items(), key=lambda kv: kv[0].value):
        schema = model.model_json_schema()
        for dep_name, dep in schema.pop("$defs", {}).items():
            defs[dep_name] = dep
        defs[model.__name__] = schema
        roots[frame.value] = model.__name__

    blocks = [_HEADER]
    for name in sorted(defs):
        blocks.append(_interface(name, defs[name]))

    entries = "\n".join(f"  {frame}: {model}" for frame, model in sorted(roots.items()))
    blocks.append(
        "/** Frames whose payload shape is generated. Anything absent stays `unknown`. */\n"
        f"export interface WsServerPayloadMap {{\n{entries}\n}}"
    )
    blocks.append("export type TypedWsFrame = keyof WsServerPayloadMap")
    return "\n\n".join(blocks) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="diff instead of writing")
    args = parser.parse_args()

    rendered = render()
    if not args.check:
        _OUT.parent.mkdir(parents=True, exist_ok=True)
        _OUT.write_text(rendered, encoding="utf-8")
        print(f"wrote {_OUT.relative_to(_REPO)}")
        return 0

    current = _OUT.read_text(encoding="utf-8") if _OUT.exists() else ""
    if current == rendered:
        print("ws-payloads.generated.ts is up to date")
        return 0
    print(
        f"{_OUT.relative_to(_REPO)} is stale.\nRun: uv run python scripts/generate_ws_types.py",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
